### ISSUE TITLE
Readme should be updated -> cmreslogging.handlers

### ISSUE THREAD

**Issue by razem-io** [cmanaha/python-elasticsearch-logger#14]
Hi,

thank you for this lib! I took me some minutes to figure out that the readme has an error;

```from cmrlogging.handlers import CMRESHandler```

should be

```from cmreslogging.handlers import CMRESHandler```

Cheers,
Julian

**Comment by cmanaha** [comment]
Will fix that on next commit. Thanks for pointing out.
