### ISSUE TITLE
Fail to handle exception log records

### ISSUE THREAD

**Issue by aldbr** [cmanaha/python-elasticsearch-logger#22]
Hello,
I encounter some troubles to send exception log records with your handler, it raises an exception in the flush method and prevents all the buffer to be sent. 
After some researches, I found the origin of the problem in the elasticsearch module that you use. Inside the module, there is a module named "serializer.py" containing a "JSONSerializer" class that does not support the exception type contained in the record.exc_info.

I see two possibilites to resolve the problem, the first is to create your own JSONSerializer which can support the exception type. You can easily pass it in the ElasticSearch constructor like this:
`self._client = Elasticsearch(hosts=self.hosts, serializer=customJSONSerializer(), ...) `
      
Indeed, the elasticsearch module is able to take custom serializer class.
The second possibility is to test if the record contains an exception type in your emit method, like this:
`if record.exc_info: 
   record.exc_info = None`

Please, just confirm this bug, I will take care of the fix in a pull request. 
Thank you in advance

**Comment by cmanaha** [comment]
Yep, I can confirm there is an issue there , feel free to send a PR

Regards 
Carlos
