### ISSUE TITLE
Missing log record fields: asctime and message in ElasticSearch

### ISSUE THREAD

**Issue by aldbr** [cmanaha/python-elasticsearch-logger#24]
Hello, 

Due to the missing *format* method call in the *emit* handler method, the log record is not formatted if we use your handler as first handler. This implies that the *asctime* and the *message* fields are not created and can not be available in ElasticSearch.
Is it your choice to improve the performances or just a bug ?

If it is a bug, I can make a pull request or just complete the current in order to solve the issue.
Thank you in advance

**Comment by cmanaha** [comment]
I'm happy to take pull requests; actually I'm happy to give others admin access to the project for the times where I might not be available to merge, test and produce/push a release.

Saludos - Cheers
Carlos

**Comment by aldbr** [comment]
I would be happy to help the project if you want to give me an admin access.

Cheers

**Comment by cmanaha** [comment]
Just added 3 of you as collaborators ( as you have posted all good PR's ); I'm sorry that I don't have much time this days to keep up with with this in a timely way.
