### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by aldbr** [cmanaha/python-elasticsearch-logger#25]
Hello @cmanaha,

Now that there is no pull request anymore, is it possible to release a new version of the handler on Pypi ? How can we proceed ? 

Thank you in advance

**Comment by cmanaha** [comment]
Not yet; The build is broken not passing flake8/pep8 guidelines (working on this now); I'd like also to update the dependencies to latest version of python elastic packages, run the tests and see if there is any other test that we can add to improve coverage before creating a final distribution.

**Comment by cmanaha** [comment]
@aldbr: Thanks a lot for the PR merging and taking care of those.  I'll do the release this weekend at the latest; Shouldn't take me long, please bear with me. No major issues found so far. I've been testing against the latest version of elastic. There were some cosmetic pep8 errors in the serialiser file (tox.ini file provided within the project to validate all those). I'd like also to add an extra test to cover the serialiser and close condition without initialisation.

**Comment by aldbr** [comment]
Alright, 
do you mean in the serialiser file that I added ? I can take a look at this.

**Comment by aldbr** [comment]
Cosmestic pep8 errors are now fixed, tox.ini validate the code.

**Comment by cmanaha** [comment]
Pipy Packages have been created, 

On the contrary, it is great to have some other people to help with it. All credit to you! 
Your changes are precisely what I was looking for before pushing for a release; Actually with your contributions and merges from others, I think we are ready to push it from beta to prod... if no one reports issues in the next few weeks I'll do that.

As for the close condition: No need to do in this release, however, looking at our coverage and considering that we are not testing authentication/authorisation as it will require integration environments that are slightly more complex to set up (or will cost money in the case of AWS settings), so the only other code where we can improve testing is in line 314, 315 (https://codecov.io/gh/cmanaha/python-elasticsearch-logger/src/master/cmreslogging/handlers.py) where our tests do only cover one of the conditions and never get into line 315, aside from that, with your latest tests we are covering all the code (not a bug-free guarantee our first try at least !).

If you are interested on the publishing part of the process, this are the relevant link sections:
To generate the wheels (once with each python2.7, python3.6 version)
 - https://packaging.python.org/tutorials/distributing-packages/#platform-wheels
Then to upload them, with the relevant account:
 - https://packaging.python.org/tutorials/distributing-packages/#upload-your-distributions

**Comment by aldbr** [comment]
Alright, thank you very much.

It is a real pleasure, I will stay tuned to fix the possible reported issues.

Fine I understand now, I will try to take a look at the line 315 during the next week if you want, and also thank you for the different link sections.
