### ISSUE TITLE
pip install CRMESHandler fails

### ISSUE THREAD

**Issue by existeundelta** [cmanaha/python-elasticsearch-logger#3]
it says:
Collecting CRMESHandler
  Could not find a version that satisfies the requirement CRMESHandler (from versions: )
No matching distribution found for CRMESHandler

**Comment by cmanaha** [comment]
Can you send some more information, platform, python version, etc would be useful. There is also tons of things to do for supporting python3 for example, feel free to amend whatever you need an send a pull request.

**Comment by existeundelta** [comment]
Was a prove on windows with 2.7, I think was just doing install, pip install CRMESHandler

**Comment by cmanaha** [comment]
Merged from patch provided by Emma Ferguson
