### ISSUE TITLE
Log traceback to ElasticSearch

### ISSUE THREAD

**Issue by physicalattraction** [cmanaha/python-elasticsearch-logger#33]
In many cases, it would be really useful to have a traceback in the logging. Would it be possible to create a setting for that and when enabled, always create a field `traceback` with the proper traceback from your program.

**Comment by cmanaha** [comment]
Sounds like an interesting optional feature... could you provide a bit more info/specification of what you would like to see and what problems you reckon it will resolve ? (just to get better context for a future implementation :) )

**Comment by physicalattraction** [comment]
I don't know how to implement it in the handler; as a user I never looked into the details of the handler. What I am currently doing is using a helper method, similar to this:

```
import logging
import sys
import traceback

def error_message(error_code, msg=None):
    data = {'error_code': error_code}
    if msg:
        data['message'] = msg
    exc_type, exc_value, exc_traceback = sys.exc_info()
    if exc_value is not None:
        data['error'] = repr(traceback.format_exception(exc_type, exc_value, exc_traceback))
    logger.error(repr(data))
```

So when logging an error, I am adding the full traceback to the error message (in a separate field). I was wondering if this could be automated somehow.

**Comment by cmanaha** [comment]
Thanks for that.  I'll take a look and check for error handling cases. I see your point.

**Comment by jensens** [comment]
why not use:
```
logger = getLogger(...)

try:
    # some code raising some Exception
except SomeException:
    logger.exception('additionalmessage')
```

**Comment by cmanaha** [comment]
@jensens: Yep, with the user story behind it, it looks to me as well more appropriate to follow that pattern. Whatever is done needs to stick both in letter and spirit to the logging framework (https://docs.python.org/3/library/logging.html) and the logger.exception fits in both categories.

From a cursory read, at least for python 3, when logger.exception is invoked, we should get the exception information as part of the log record (exc_info). From there we should be able to extract the stack and make sure it ends in elastic.

**Comment by physicalattraction** [comment]
I also learned recently that the function `log` (and 'error', 'critical', etc.) has an optional parameter `exc_info`, which prints the traceback when set to `True`.

**Comment by cmanaha** [comment]
logger.exception() it is then... we are already taking it in, but the format of the field is not right when the code sends it over to elastic. logger.exception("msg") ends up as an entry "<class 'Exception'>, msg, <traceback object at 0x10ca5d808>"... just a few lines extras will be required to transform with traceback. Will add this as soon as I have some time (or will take PR's if anyone is interested).
