### ISSUE TITLE
Logs are not appearing in AWS ElasticSearch service from Python Lambda

### ISSUE THREAD

**Issue by kottaravikumar** [cmanaha/python-elasticsearch-logger#60]
We are trying to send logs from Lambda to Elastic search using the code snippet below. We are not getting any error and not appearing logs in elastic search.

[Code Snippet](https://gist.github.com/kottaravikumar/73d9e6c46f13ca646cf156f2cc8e61d2)
Can someone please help me to resolve the issue?

**Comment by liampauling** [comment]
Is the script running long enough to be flushed?
