### ISSUE TITLE
Me and my team are willing to have contributors to our fork

### ISSUE THREAD

**Issue by Rockin2** [cmanaha/python-elasticsearch-logger#81]
https://github.com/IMInterne/python-elasticsearch-ecs-logger

The biggest change is we follow ECS for fields names and values.

**Comment by javiermatos** [comment]
I have used this new fork as a replacement and it works fine. It fixes #76, which was my issue.

Thank you!

**Comment by Rockin2** [comment]
You're welcome! :)

**Comment by martinschi** [comment]
> https://github.com/IMInterne/python-elasticsearch-ecs-logger
> 
> The biggest change is we follow ECS for fields names and values.

@Rockin2 Why are Issues not enabled in https://github.com/IMInterne/python-elasticsearch-ecs-logger?

**Comment by ffMathy** [comment]
> > https://github.com/IMInterne/python-elasticsearch-ecs-logger
> > The biggest change is we follow ECS for fields names and values.
> 
> @Rockin2 Why are Issues not enabled in https://github.com/IMInterne/python-elasticsearch-ecs-logger?

I think that's default when you fork for some reason in GitHub.

@Rockin2 can you enable it?

**Comment by Rockin2** [comment]
Hi everyone. Unfortunately, I stopped to work for InnovMetric in 2021. I don’t have the right to modify the repository’s setting. :(

**Comment by Rockin2** [comment]
You can check one of the forks of this repository if you want to use it.
