### ISSUE TITLE
Message is empty

### ISSUE THREAD

**Issue by hstadler** [cmanaha/python-elasticsearch-logger#9]
Hi,

I'm having a problem using _args_ in log calls, as this leads to an empty `message` (the log record seems not have this attribute) when this is the only logging handler. For example a `log.info('The value is: %s', some_value)` gives me an empty `message` and `msg` just holds the log string `The value is: %s` (without the _args_ substituted).

Not sure if I'm using it wrong or how to get the whole log message transmitted. I would be glad if you can give me a hint. Thx!

I'm using `logging.config.dictConfig` to configure logging with the following dict:
```
{
	"version": 1,
	"incremental": false,
	"formatters":
	{
		"simple":
		{
			"format": "%(message)s"
		}
	},
	"handlers":
	{
		"elasticsearch":
		{
			"class": "cmreshandler.cmreshandler.CMRESHandler",
			"level": "DEBUG",
			"formatter": "simple",
			"hosts": [
				{
					"host": "127.0.0.1",
					"port": 9200
				}
			],
			"auth_type": "ext://cmreshandler.cmreshandler.CMRESHandler.AuthType.NO_AUTH",
			"es_index_name": "myapp"
		}
	},
	"root":
	{
		"level": "DEBUG",
		"handlers": ["elasticsearch"]
	}
}
```

**Comment by cmanaha** [comment]
just a quick heads up. I'm trying to reproduce this issue and find the cause.

**Comment by hstadler** [comment]
Thx for your reply and sorry for this late response:

I don't think the syntax `log.info('The value is: %s', some_value)` is incorrect, because it is described in the Python 2.7 logging documentation and howtos. This is relevant (I think not only) for me, because I use libraries like SQLAlchemy, etc. that use that syntax too.

For me a workaround using a filter that creates the message mimics the behaviour:
```
class CMRESFixFilter(logging.Filter):
    def filter(self, record):
        if not hasattr(record, 'message'):
            record.message = record.getMessage()
        return 1
```
and adding `'args'` to `__LOGGING_FILTER_FIELDS` as the serialization might fail (_TypeError: Unable to serialize xyz_) when the log record is sent.
